### PR TITLE
Added tutorial pages

### PR DESCRIPTION
**Pull request by optixyt0**

### CODE REVIEW

**Comment by Twin1dev** [comment]
this is just lawin server bro

**Comment by optixyt0** [comment]
Bro. why does everyone hate me all of a sudden coz i used one example from lawin
this world is insane.

**Comment by MarvelcoOGFN** [comment]
> Bro. why does everyone hate me all of a sudden coz i used one example from lawin this world is insane.

yes bro making a pr to a wiki with skidded code is a great example

**Comment by Rypex0** [comment]
womp womp

**Comment by optixyt0** [comment]
bruh shut up






---- On Fri, 11 Oct 2024 16:30:09 +0100 Marvelco ***@***.***> wrote ---





Bro. why does everyone hate me all of a sudden coz i used one example from lawin this world is insane.


yes bro making a pr to a wiki with skidded code is a great example

**Comment by optixyt0** [comment]
> womp womp

Stop being marvs little pet, we know you are only following his opinion coz he is popular and you don't want to be on his 'bad side'

**Pull request closed without merging**
